server:
  port: 8080

spring:
  application:
    name: rootme
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false # false for dev mode

logging:
  level:
    ROOT: INFO