spring:
  application:
    name: rootme
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url:
    username:
    password: