server:
  port: 8080

spring:
  application:
    name: rootme
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rootme_db
    username: rootme_adm
    password: 12345
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false # false for dev mode

logging:
  level:
    ROOT: INFO