spring:
  application:
    name: rootme
  port: 8080
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rootme_db
    username: rootme_adm
    password: 12345

logging:
  level:
    ROOT: INFO